var group___r_e_n_e_s_a_s___c_o_n_n_e_c_t_i_v_i_t_y___m_o_d_u_l_e_s =
[
    [ "Azure RTOS USBX Port (rm_usbx_port)", "group___u_s_b_x.html", null ],
    [ "CAN (r_can)", "group___c_a_n.html", "group___c_a_n" ],
    [ "CAN FD (r_canfd)", "group___c_a_n_f_d.html", "group___c_a_n_f_d" ],
    [ "CEC (r_cec)", "group___c_e_c.html", "group___c_e_c" ],
    [ "I2C Communication Device (rm_comms_i2c)", "group___r_m___c_o_m_m_s___i2_c.html", "group___r_m___c_o_m_m_s___i2_c" ],
    [ "I2C Master (r_iic_b_master)", "group___i_i_c___b___m_a_s_t_e_r.html", "group___i_i_c___b___m_a_s_t_e_r" ],
    [ "I2C Master (r_iic_master)", "group___i_i_c___m_a_s_t_e_r.html", "group___i_i_c___m_a_s_t_e_r" ],
    [ "I2C Master (r_iica_master)", "group___i_i_c_a___m_a_s_t_e_r.html", "group___i_i_c_a___m_a_s_t_e_r" ],
    [ "I2C Master (r_sau_i2c)", "group___s_a_u___i2_c.html", "group___s_a_u___i2_c" ],
    [ "I2C Master (r_sci_b_i2c)", "group___s_c_i___b___i2_c.html", "group___s_c_i___b___i2_c" ],
    [ "I2C Master (r_sci_i2c)", "group___s_c_i___i2_c.html", "group___s_c_i___i2_c" ],
    [ "I2C Slave (r_iic_b_slave)", "group___i_i_c___b___s_l_a_v_e.html", "group___i_i_c___b___s_l_a_v_e" ],
    [ "I2C Slave (r_iic_slave)", "group___i_i_c___s_l_a_v_e.html", "group___i_i_c___s_l_a_v_e" ],
    [ "I2C Slave (r_iica_slave)", "group___i_i_c_a___s_l_a_v_e.html", "group___i_i_c_a___s_l_a_v_e" ],
    [ "I2S (r_ssi)", "group___s_s_i.html", "group___s_s_i" ],
    [ "I3C (r_i3c)", "group___i3_c.html", "group___i3_c" ],
    [ "LIN (r_sau_lin)", "group___s_a_u___l_i_n.html", "group___s_a_u___l_i_n" ],
    [ "LIN (r_sci_b_lin)", "group___s_c_i___b___l_i_n.html", "group___s_c_i___b___l_i_n" ],
    [ "LIN (r_sci_lin)", "group___s_c_i___l_i_n.html", "group___s_c_i___l_i_n" ],
    [ "SMBUS Communication Device (rm_comms_smbus)", "group___r_m___c_o_m_m_s___s_m_b_u_s.html", "group___r_m___c_o_m_m_s___s_m_b_u_s" ],
    [ "SMCI (r_sci_smci)", "group___s_c_i___s_m_c_i.html", "group___s_c_i___s_m_c_i" ],
    [ "SPI (r_sau_spi)", "group___s_a_u___s_p_i.html", "group___s_a_u___s_p_i" ],
    [ "SPI (r_sci_b_spi)", "group___s_c_i___b___s_p_i.html", "group___s_c_i___b___s_p_i" ],
    [ "SPI (r_sci_spi)", "group___s_c_i___s_p_i.html", "group___s_c_i___s_p_i" ],
    [ "SPI (r_spi)", "group___s_p_i.html", "group___s_p_i" ],
    [ "SPI (r_spi_b)", "group___s_p_i___b.html", "group___s_p_i___b" ],
    [ "SPI Communication Device (rm_comms_spi)", "group___r_m___c_o_m_m_s___s_p_i.html", "group___r_m___c_o_m_m_s___s_p_i" ],
    [ "UART (r_sau_uart)", "group___s_a_u___u_a_r_t.html", "group___s_a_u___u_a_r_t" ],
    [ "UART (r_sci_b_uart)", "group___s_c_i___b___u_a_r_t.html", "group___s_c_i___b___u_a_r_t" ],
    [ "UART (r_sci_uart)", "group___s_c_i___u_a_r_t.html", "group___s_c_i___u_a_r_t" ],
    [ "UART (r_uarta)", "group___u_a_r_t_a.html", "group___u_a_r_t_a" ],
    [ "UART Communication Device (rm_comms_uart)", "group___r_m___c_o_m_m_s___u_a_r_t.html", "group___r_m___c_o_m_m_s___u_a_r_t" ],
    [ "USB (r_usb_basic)", "group___u_s_b.html", "group___u_s_b" ],
    [ "USB Composite (r_usb_composite)", "group___u_s_b___c_o_m_p_o_s_i_t_e.html", null ],
    [ "USB HCDC (r_usb_hcdc)", "group___u_s_b___h_c_d_c.html", "group___u_s_b___h_c_d_c" ],
    [ "USB HCDC_ECM (r_usb_hcdc_ecm)", "group___u_s_b___h_c_d_c___e_c_m.html", "group___u_s_b___h_c_d_c___e_c_m" ],
    [ "USB HHID (r_usb_hhid)", "group___u_s_b___h_h_i_d.html", "group___u_s_b___h_h_i_d" ],
    [ "USB HMSC (r_usb_hmsc)", "group___u_s_b___h_m_s_c.html", "group___u_s_b___h_m_s_c" ],
    [ "USB Host Vendor class (r_usb_hvnd)", "group___u_s_b___h_v_n_d.html", null ],
    [ "USB PCDC (r_usb_pcdc)", "group___u_s_b___p_c_d_c.html", null ],
    [ "USB PHID (r_usb_phid)", "group___u_s_b___p_h_i_d.html", null ],
    [ "USB PMSC (r_usb_pmsc)", "group___u_s_b___p_m_s_c.html", null ],
    [ "USB PPRN (r_usb_pprn)", "group___u_s_b___p_p_r_n.html", null ],
    [ "USB Peripheral Vendor class (r_usb_pvnd)", "group___u_s_b___p_v_n_d.html", null ],
    [ "USB-TYPEC (r_usb_typec)", "group___u_s_b___t_y_p_e_c.html", "group___u_s_b___t_y_p_e_c" ],
    [ "USB_PCDC Communication Device (rm_comms_usb_pcdc)", "group___r_m___c_o_m_m_s___u_s_b___p_c_d_c.html", "group___r_m___c_o_m_m_s___u_s_b___p_c_d_c" ]
];