var group___r_e_n_e_s_a_s___m_o_d_u_l_e_s =
[
    [ "High-Speed Analog Comparator (r_acmphs)", "group___a_c_m_p_h_s.html", "group___a_c_m_p_h_s" ],
    [ "Low-Power Analog Comparator (r_acmplp)", "group___a_c_m_p_l_p.html", "group___a_c_m_p_l_p" ],
    [ "Analog to Digital Converter (r_adc)", "group___a_d_c.html", "group___a_d_c" ],
    [ "Asynchronous General Purpose Timer (r_agt)", "group___a_g_t.html", "group___a_g_t" ],
    [ "Clock Frequency Accuracy Measurement Circuit (r_cac)", "group___c_a_c.html", "group___c_a_c" ],
    [ "Clock Generation Circuit (r_cgc)", "group___c_g_c.html", "group___c_g_c" ],
    [ "Cyclic Redundancy Check (CRC) Calculator (r_crc)", "group___c_r_c.html", "group___c_r_c" ],
    [ "Capacitive Touch Sensing Unit (r_ctsu)", "group___c_t_s_u.html", "group___c_t_s_u" ],
    [ "Digital to Analog Converter (r_dac)", "group___d_a_c.html", "group___d_a_c" ],
    [ "Direct Memory Access Controller (r_dmac)", "group___d_m_a_c.html", "group___d_m_a_c" ],
    [ "Data Operation Circuit (r_doc)", "group___d_o_c.html", "group___d_o_c" ],
    [ "D/AVE 2D Port Interface (r_drw)", "group___d_r_w.html", null ],
    [ "Data Transfer Controller (r_dtc)", "group___d_t_c.html", "group___d_t_c" ],
    [ "Event Link Controller (r_elc)", "group___e_l_c.html", "group___e_l_c" ],
    [ "Ethernet (r_ether)", "group___e_t_h_e_r.html", "group___e_t_h_e_r" ],
    [ "Ethernet PHY (r_ether_phy)", "group___e_t_h_e_r___p_h_y.html", "group___e_t_h_e_r___p_h_y" ],
    [ "High-Performance Flash Driver (r_flash_hp)", "group___f_l_a_s_h___h_p.html", "group___f_l_a_s_h___h_p" ],
    [ "Low-Power Flash Driver (r_flash_lp)", "group___f_l_a_s_h___l_p.html", "group___f_l_a_s_h___l_p" ],
    [ "Graphics LCD Controller (r_glcdc)", "group___g_l_c_d_c.html", "group___g_l_c_d_c" ],
    [ "General PWM Timer (r_gpt)", "group___g_p_t.html", "group___g_p_t" ],
    [ "Interrupt Controller Unit (r_icu)", "group___i_c_u.html", "group___i_c_u" ],
    [ "I2C Master on IIC (r_iic_master)", "group___i_i_c___m_a_s_t_e_r.html", "group___i_i_c___m_a_s_t_e_r" ],
    [ "I2C Slave on IIC (r_iic_slave)", "group___i_i_c___s_l_a_v_e.html", "group___i_i_c___s_l_a_v_e" ],
    [ "I/O Ports (r_ioport)", "group___i_o_p_o_r_t.html", "group___i_o_p_o_r_t" ],
    [ "Independent Watchdog Timer (r_iwdt)", "group___i_w_d_t.html", "group___i_w_d_t" ],
    [ "JPEG Codec (r_jpeg)", "group___j_p_e_g.html", "group___j_p_e_g" ],
    [ "Key Interrupt (r_kint)", "group___k_i_n_t.html", "group___k_i_n_t" ],
    [ "Low Power Modes (r_lpm)", "group___l_p_m.html", "group___l_p_m" ],
    [ "Low Voltage Detection (r_lvd)", "group___l_v_d.html", "group___l_v_d" ],
    [ "Realtime Clock (r_rtc)", "group___r_t_c.html", "group___r_t_c" ],
    [ "Serial Communications Interface (SCI) I2C (r_sci_i2c)", "group___s_c_i___i2_c.html", "group___s_c_i___i2_c" ],
    [ "Serial Communications Interface (SCI) SPI (r_sci_spi)", "group___s_c_i___s_p_i.html", "group___s_c_i___s_p_i" ],
    [ "Serial Communications Interface (SCI) UART (r_sci_uart)", "group___s_c_i___u_a_r_t.html", "group___s_c_i___u_a_r_t" ],
    [ "SD/MMC Host Interface (r_sdhi)", "group___s_d_h_i.html", "group___s_d_h_i" ],
    [ "Serial Peripheral Interface (r_spi)", "group___s_p_i.html", "group___s_p_i" ],
    [ "Serial Sound Interface (r_ssi)", "group___s_s_i.html", "group___s_s_i" ],
    [ "Universal Serial Bus (r_usb_basic)", "group___u_s_b.html", "group___u_s_b" ],
    [ "Host Mass Storage Class Driver (r_usb_hmsc)", "group___u_s_b___h_m_s_c.html", null ],
    [ "Universal Serial Bus Peripheral Communication Device Class (r_usb_pcdc)", "group___u_s_b___p_c_d_c.html", null ],
    [ "Watchdog Timer (r_wdt)", "group___w_d_t.html", "group___w_d_t" ],
    [ "SEGGER emWin Port (rm_emwin_port)", "group___r_m___e_m_w_i_n___p_o_r_t.html", null ],
    [ "FreeRTOS Plus FAT (rm_freertos_plus_fat)", "group___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t.html", "group___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t" ],
    [ "Amazon FreeRTOS Port (rm_freertos_port)", "group___r_m___f_r_e_e_r_t_o_s___p_o_r_t.html", null ],
    [ "Crypto Middleware (rm_psa_crypto)", "group___r_m___p_s_a___c_r_y_p_t_o.html", "group___r_m___p_s_a___c_r_y_p_t_o" ],
    [ "Capacitive Touch Middleware (rm_touch)", "group___t_o_u_c_h.html", "group___t_o_u_c_h" ]
];