var group___r_e_n_e_s_a_s___m_o_d_u_l_e_s =
[
    [ "High-Speed Analog Comparator (r_acmphs)", "group___a_c_m_p_h_s.html", "group___a_c_m_p_h_s" ],
    [ "Low-Power Analog Comparator (r_acmplp)", "group___a_c_m_p_l_p.html", "group___a_c_m_p_l_p" ],
    [ "Analog to Digital Converter (r_adc)", "group___a_d_c.html", "group___a_d_c" ],
    [ "Analog to Digital Converter (r_adc_b)", "group___a_d_c___b.html", "group___a_d_c___b" ],
    [ "Asynchronous General Purpose Timer (r_agt)", "group___a_g_t.html", "group___a_g_t" ],
    [ "Bluetooth Low Energy Library of Balance Configuration (r_ble)", "group___b_l_e___b_a_l_a_n_c_e.html", null ],
    [ "Bluetooth Low Energy Library of Compact Configuration (r_ble)", "group___b_l_e___c_o_m_p_a_c_t.html", null ],
    [ "Bluetooth Low Energy Library of Extended Configuration (r_ble)", "group___b_l_e___e_x_t_e_n_d_e_d.html", null ],
    [ "Clock Frequency Accuracy Measurement Circuit (r_cac)", "group___c_a_c.html", "group___c_a_c" ],
    [ "Controller Area Network (r_can)", "group___c_a_n.html", "group___c_a_n" ],
    [ "Controller Area Network - Flexible Data (r_canfd)", "group___c_a_n_f_d.html", "group___c_a_n_f_d" ],
    [ "Consumer Electronics Control (r_cec)", "group___c_e_c.html", "group___c_e_c" ],
    [ "Clock Generation Circuit (r_cgc)", "group___c_g_c.html", "group___c_g_c" ],
    [ "Cyclic Redundancy Check (CRC) Calculator (r_crc)", "group___c_r_c.html", "group___c_r_c" ],
    [ "Capacitive Touch Sensing Unit (r_ctsu)", "group___c_t_s_u.html", "group___c_t_s_u" ],
    [ "Digital to Analog Converter (r_dac)", "group___d_a_c.html", "group___d_a_c" ],
    [ "Digital to Analog Converter (r_dac8)", "group___d_a_c8.html", "group___d_a_c8" ],
    [ "Direct Memory Access Controller (r_dmac)", "group___d_m_a_c.html", "group___d_m_a_c" ],
    [ "Data Operation Circuit (r_doc)", "group___d_o_c.html", "group___d_o_c" ],
    [ "D/AVE 2D Port Interface (r_drw)", "group___d_r_w.html", null ],
    [ "Data Transfer Controller (r_dtc)", "group___d_t_c.html", "group___d_t_c" ],
    [ "Event Link Controller (r_elc)", "group___e_l_c.html", "group___e_l_c" ],
    [ "Ethernet (r_ether)", "group___e_t_h_e_r.html", "group___e_t_h_e_r" ],
    [ "Ethernet PHY (r_ether_phy)", "group___e_t_h_e_r___p_h_y.html", "group___e_t_h_e_r___p_h_y" ],
    [ "High-Performance Flash Driver (r_flash_hp)", "group___f_l_a_s_h___h_p.html", "group___f_l_a_s_h___h_p" ],
    [ "Low-Power Flash Driver (r_flash_lp)", "group___f_l_a_s_h___l_p.html", "group___f_l_a_s_h___l_p" ],
    [ "Graphics LCD Controller (r_glcdc)", "group___g_l_c_d_c.html", "group___g_l_c_d_c" ],
    [ "General PWM Timer (r_gpt)", "group___g_p_t.html", "group___g_p_t" ],
    [ "General PWM Timer Three-Phase Motor Control Driver (r_gpt_three_phase)", "group___g_p_t___t_h_r_e_e___p_h_a_s_e.html", "group___g_p_t___t_h_r_e_e___p_h_a_s_e" ],
    [ "I3C Bus Interface (r_i3c)", "group___i3_c.html", "group___i3_c" ],
    [ "Interrupt Controller Unit (r_icu)", "group___i_c_u.html", "group___i_c_u" ],
    [ "I2C Master on IIC/I3C (r_iic_b_master)", "group___i_i_c___b___m_a_s_t_e_r.html", "group___i_i_c___b___m_a_s_t_e_r" ],
    [ "I2C Slave on IIC/I3C (r_iic_b_slave)", "group___i_i_c___b___s_l_a_v_e.html", "group___i_i_c___b___s_l_a_v_e" ],
    [ "I2C Master on IIC (r_iic_master)", "group___i_i_c___m_a_s_t_e_r.html", "group___i_i_c___m_a_s_t_e_r" ],
    [ "I2C Slave on IIC (r_iic_slave)", "group___i_i_c___s_l_a_v_e.html", "group___i_i_c___s_l_a_v_e" ],
    [ "I/O Ports (r_ioport)", "group___i_o_p_o_r_t.html", "group___i_o_p_o_r_t" ],
    [ "Independent Watchdog Timer (r_iwdt)", "group___i_w_d_t.html", "group___i_w_d_t" ],
    [ "JPEG Codec (r_jpeg)", "group___j_p_e_g.html", "group___j_p_e_g" ],
    [ "Key Interrupt (r_kint)", "group___k_i_n_t.html", "group___k_i_n_t" ],
    [ "Low Power Modes (r_lpm)", "group___l_p_m.html", "group___l_p_m" ],
    [ "Low Voltage Detection (r_lvd)", "group___l_v_d.html", "group___l_v_d" ],
    [ "Operational Amplifier (r_opamp)", "group___o_p_a_m_p.html", "group___o_p_a_m_p" ],
    [ "Octa Serial Peripheral Interface for Flash and RAM devices (r_ospi)", "group___o_s_p_i.html", "group___o_s_p_i" ],
    [ "Parallel Data Capture (r_pdc)", "group___p_d_c.html", "group___p_d_c" ],
    [ "Port Output Enable for GPT (r_poeg)", "group___p_o_e_g.html", "group___p_o_e_g" ],
    [ "Precision Time Protocol (r_ptp)", "group___p_t_p.html", "group___p_t_p" ],
    [ "Quad Serial Peripheral Interface Flash (r_qspi)", "group___q_s_p_i.html", "group___q_s_p_i" ],
    [ "Realtime Clock (r_rtc)", "group___r_t_c.html", "group___r_t_c" ],
    [ "Secure Crypto Engine (r_sce_protected)", "group___s_c_e___p_r_o_t_e_c_t_e_d.html", "group___s_c_e___p_r_o_t_e_c_t_e_d" ],
    [ "Serial Communications Interface (SCI) I2C (r_sci_b_i2c)", "group___s_c_i___b___i2_c.html", "group___s_c_i___b___i2_c" ],
    [ "Serial Communications Interface (SCI) SPI (r_sci_b_spi)", "group___s_c_i___b___s_p_i.html", "group___s_c_i___b___s_p_i" ],
    [ "Serial Communications Interface (SCI) UART (r_sci_b_uart)", "group___s_c_i___b___u_a_r_t.html", "group___s_c_i___b___u_a_r_t" ],
    [ "Serial Communications Interface (SCI) I2C (r_sci_i2c)", "group___s_c_i___i2_c.html", "group___s_c_i___i2_c" ],
    [ "Serial Communications Interface (SCI) SPI (r_sci_spi)", "group___s_c_i___s_p_i.html", "group___s_c_i___s_p_i" ],
    [ "Serial Communications Interface (SCI) UART (r_sci_uart)", "group___s_c_i___u_a_r_t.html", "group___s_c_i___u_a_r_t" ],
    [ "Sigma Delta Analog to Digital Converter (r_sdadc)", "group___s_d_a_d_c.html", "group___s_d_a_d_c" ],
    [ "SD/MMC Host Interface (r_sdhi)", "group___s_d_h_i.html", "group___s_d_h_i" ],
    [ "Segment LCD Controller (r_slcdc)", "group___s_l_c_d_c.html", "group___s_l_c_d_c" ],
    [ "Serial Peripheral Interface (r_spi)", "group___s_p_i.html", "group___s_p_i" ],
    [ "Serial Peripheral Interface (r_spi_b)", "group___s_p_i___b.html", "group___s_p_i___b" ],
    [ "Serial Sound Interface (r_ssi)", "group___s_s_i.html", "group___s_s_i" ],
    [ "USB (r_usb_basic)", "group___u_s_b.html", "group___u_s_b" ],
    [ "USB Composite Class (r_usb_composite)", "group___u_s_b___c_o_m_p_o_s_i_t_e.html", null ],
    [ "USB Host Communications Device Class Driver (r_usb_hcdc)", "group___u_s_b___h_c_d_c.html", null ],
    [ "USB Host Human Interface Device Class Driver (r_usb_hhid)", "group___u_s_b___h_h_i_d.html", "group___u_s_b___h_h_i_d" ],
    [ "USB Host Mass Storage Class Driver (r_usb_hmsc)", "group___u_s_b___h_m_s_c.html", "group___u_s_b___h_m_s_c" ],
    [ "USB Host Vendor Class (r_usb_hvnd)", "group___u_s_b___h_v_n_d.html", null ],
    [ "USB Peripheral Communications Device Class (r_usb_pcdc)", "group___u_s_b___p_c_d_c.html", null ],
    [ "USB Peripheral Human Interface Device Class (r_usb_phid)", "group___u_s_b___p_h_i_d.html", null ],
    [ "USB Peripheral Mass Storage Class (r_usb_pmsc)", "group___u_s_b___p_m_s_c.html", null ],
    [ "USB Peripheral Vendor Class (r_usb_pvnd)", "group___u_s_b___p_v_n_d.html", null ],
    [ "Watchdog Timer (r_wdt)", "group___w_d_t.html", "group___w_d_t" ],
    [ "ADPCM Decoder (rm_adpcm_decoder)", "group___r_m___a_d_p_c_m___d_e_c_o_d_e_r.html", "group___r_m___a_d_p_c_m___d_e_c_o_d_e_r" ],
    [ "Audio Playback with PWM (rm_audio_playback_pwm)", "group___r_m___a_u_d_i_o___p_l_a_y_b_a_c_k___p_w_m.html", "group___r_m___a_u_d_i_o___p_l_a_y_b_a_c_k___p_w_m" ],
    [ "AWS PKCS11 PAL (rm_aws_pkcs11_pal)", "group___a_w_s___p_k_c_s11___p_a_l.html", null ],
    [ "AWS PKCS11 PAL LITTLEFS (rm_aws_pkcs11_pal_littlefs)", "group___a_w_s___p_k_c_s11___p_a_l___l_i_t_t_l_e_f_s.html", null ],
    [ "Bluetooth Low Energy Abstraction (rm_ble_abs)", "group___b_l_e___a_b_s.html", "group___b_l_e___a_b_s" ],
    [ "Bluetooth Low Energy Abstraction with RYZ012 (rm_ble_abs_spp)", "group___b_l_e___a_b_s___s_p_p.html", null ],
    [ "SD/MMC Block Media Implementation (rm_block_media_sdmmc)", "group___r_m___b_l_o_c_k___m_e_d_i_a___s_d_m_m_c.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___s_d_m_m_c" ],
    [ "SPI Block Media Implementation (rm_block_media_spi)", "group___r_m___b_l_o_c_k___m_e_d_i_a___s_p_i.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___s_p_i" ],
    [ "USB HMSC Block Media Implementation (rm_block_media_usb)", "group___r_m___b_l_o_c_k___m_e_d_i_a___u_s_b.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___u_s_b" ],
    [ "User Block Media Implementation (rm_block_media_user)", "group___r_m___b_l_o_c_k___m_e_d_i_a___u_s_e_r.html", null ],
    [ "I2C Communicatons Middleware (rm_comms_i2c)", "group___r_m___c_o_m_m_s___i2_c.html", "group___r_m___c_o_m_m_s___i2_c" ],
    [ "SEGGER emWin Port (rm_emwin_port)", "group___r_m___e_m_w_i_n___p_o_r_t.html", null ],
    [ "Azure RTOS FileX Block Media I/O Driver (rm_filex_block_media)", "group___r_m___f_i_l_e_x___b_l_o_c_k___m_e_d_i_a.html", "group___r_m___f_i_l_e_x___b_l_o_c_k___m_e_d_i_a" ],
    [ "Azure RTOS FileX LevelX I/O Driver (rm_filex_levelx_nor)", "group___r_m___f_i_l_e_x___l_e_v_e_l_x___n_o_r.html", "group___r_m___f_i_l_e_x___l_e_v_e_l_x___n_o_r" ],
    [ "FreeRTOS+FAT Port (rm_freertos_plus_fat)", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t.html", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t" ],
    [ "FreeRTOS Plus TCP (rm_freertos_plus_tcp)", "group___f_r_e_e_r_t_o_s___p_l_u_s___t_c_p.html", null ],
    [ "FreeRTOS Port (rm_freertos_port)", "group___r_m___f_r_e_e_r_t_o_s___p_o_r_t.html", null ],
    [ "RTOS Context Management (rm_tz_context)", "group___r_m___t_z___c_o_n_t_e_x_t.html", null ],
    [ "FS2012 Sensor Middleware (rm_fs2012)", "group___r_m___f_s2012.html", "group___r_m___f_s2012" ],
    [ "Azure RTOS GUIX Port (rm_guix_port)", "group___r_m___g_u_i_x___p_o_r_t.html", "group___r_m___g_u_i_x___p_o_r_t" ],
    [ "HS300X Sensor Middleware (rm_hs300x)", "group___r_m___h_s300_x.html", "group___r_m___h_s300_x" ],
    [ "Azure RTOS LevelX NOR SPI Driver (rm_levelx_nor_spi)", "group___r_m___l_e_v_e_l_x___n_o_r___s_p_i.html", "group___r_m___l_e_v_e_l_x___n_o_r___s_p_i" ],
    [ "LittleFS Flash Port (rm_littlefs_flash)", "group___r_m___l_i_t_t_l_e_f_s___f_l_a_s_h.html", "group___r_m___l_i_t_t_l_e_f_s___f_l_a_s_h" ],
    [ "MCUboot Port (rm_mcuboot_port)", "group___r_m___m_c_u_b_o_o_t___p_o_r_t.html", null ],
    [ "Motor 120 Control Hall (motor_120_control_hall)", "group___m_o_t_o_r__120___c_o_n_t_r_o_l___h_a_l_l.html", "group___m_o_t_o_r__120___c_o_n_t_r_o_l___h_a_l_l" ],
    [ "Motor 120 Control Sensorless (motor_120_control_sensorless)", "group___m_o_t_o_r__120___c_o_n_t_r_o_l___s_e_n_s_o_r_l_e_s_s.html", "group___m_o_t_o_r__120___c_o_n_t_r_o_l___s_e_n_s_o_r_l_e_s_s" ],
    [ "Motor 120 Degree (rm_motor_120_degree)", "group___m_o_t_o_r__120___d_e_g_r_e_e.html", "group___m_o_t_o_r__120___d_e_g_r_e_e" ],
    [ "Motor 120 degree driver (rm_motor_120_driver)", "group___m_o_t_o_r__120___d_r_i_v_e_r.html", "group___m_o_t_o_r__120___d_r_i_v_e_r" ],
    [ "Motor Current (rm_motor_current)", "group___m_o_t_o_r___c_u_r_r_e_n_t.html", "group___m_o_t_o_r___c_u_r_r_e_n_t" ],
    [ "Motor Driver (rm_motor_driver)", "group___m_o_t_o_r___d_r_i_v_e_r.html", "group___m_o_t_o_r___d_r_i_v_e_r" ],
    [ "Motor encoder vector control (rm_motor_encoder)", "group___m_o_t_o_r___e_n_c_o_d_e_r.html", "group___m_o_t_o_r___e_n_c_o_d_e_r" ],
    [ "Motor Angle and Speed Estimation (rm_motor_estimate)", "group___m_o_t_o_r___e_s_t_i_m_a_t_e.html", "group___m_o_t_o_r___e_s_t_i_m_a_t_e" ],
    [ "Motor Position (rm_motor_position)", "group___m_o_t_o_r___p_o_s_i_t_i_o_n.html", "group___m_o_t_o_r___p_o_s_i_t_i_o_n" ],
    [ "Motor Angle and Speed Calculation with an Encoder (rm_motor_sense_encoder)", "group___m_o_t_o_r___s_e_n_s_e___e_n_c_o_d_e_r.html", "group___m_o_t_o_r___s_e_n_s_e___e_n_c_o_d_e_r" ],
    [ "Motor Sensorless Vector Control (rm_motor_sensorless)", "group___m_o_t_o_r___s_e_n_s_o_r_l_e_s_s.html", "group___m_o_t_o_r___s_e_n_s_o_r_l_e_s_s" ],
    [ "Motor Speed (rm_motor_speed)", "group___m_o_t_o_r___s_p_e_e_d.html", "group___m_o_t_o_r___s_p_e_e_d" ],
    [ "Azure RTOS NetX Secure Crypto Hardware Acceleration (rm_netx_secure_crypto)", "group___r_m___n_e_t_x___s_e_c_u_r_e___c_r_y_p_t_o.html", null ],
    [ "Azure RTOS NetX Duo Ether Driver (rm_netxduo_ether)", "group___r_m___n_e_t_x_d_u_o___e_t_h_e_r.html", null ],
    [ "Azure RTOS NetX Duo WiFi Driver (rm_netxduo_wifi)", "group___r_m___n_e_t_x_d_u_o___w_i_f_i.html", null ],
    [ "Crypto Middleware (rm_psa_crypto)", "group___r_m___p_s_a___c_r_y_p_t_o.html", "group___r_m___p_s_a___c_r_y_p_t_o" ],
    [ "Azure RTOS ThreadX Port (rm_threadx_port)", "group___r_m___t_h_r_e_a_d_x___p_o_r_t.html", null ],
    [ "Intel TinyCrypt (rm_tinycrypt_port)", "group___r_m___t_i_n_y_c_r_y_p_t___p_o_r_t.html", "group___r_m___t_i_n_y_c_r_y_p_t___p_o_r_t" ],
    [ "Capacitive Touch Middleware (rm_touch)", "group___t_o_u_c_h.html", "group___t_o_u_c_h" ],
    [ "USBX Porting Layer (rm_usbx_port)", "group___u_s_b_x.html", null ],
    [ "Virtual EEPROM (rm_vee_flash)", "group___r_m___v_e_e___f_l_a_s_h.html", "group___r_m___v_e_e___f_l_a_s_h" ],
    [ "AWS Device Provisioning", "group___d_e_v_i_c_e___p_r_o_v_i_s_i_o_n_i_n_g.html", null ],
    [ "AWS HTTPS", "group___a_w_s___h_t_t_p_s.html", null ],
    [ "AWS MQTT", "group___a_w_s___m_q_t_t.html", null ],
    [ "Wifi Middleware (rm_wifi_onchip_silex)", "group___w_i_f_i___o_n_c_h_i_p___s_i_l_e_x.html", "group___w_i_f_i___o_n_c_h_i_p___s_i_l_e_x" ],
    [ "AWS Secure Sockets", "group___a_w_s___s_e_c_u_r_e___s_o_c_k_e_t_s.html", null ],
    [ "ZMOD4XXX Sensor Middleware (rm_zmod4xxx)", "group___r_m___z_m_o_d4_x_x_x.html", "group___r_m___z_m_o_d4_x_x_x" ]
];