var group___r_e_n_e_s_a_s___i_n_t_e_r_f_a_c_e_s =
[
    [ "ADC Interface", "group___a_d_c___a_p_i.html", "group___a_d_c___a_p_i" ],
    [ "BLE Interface", "group___b_l_e___a_p_i.html", "group___b_l_e___a_p_i" ],
    [ "CAC Interface", "group___c_a_c___a_p_i.html", "group___c_a_c___a_p_i" ],
    [ "CAN Interface", "group___c_a_n___a_p_i.html", "group___c_a_n___a_p_i" ],
    [ "CEC Interface", "group___c_e_c___a_p_i.html", "group___c_e_c___a_p_i" ],
    [ "CGC Interface", "group___c_g_c___a_p_i.html", "group___c_g_c___a_p_i" ],
    [ "Comparator Interface", "group___c_o_m_p_a_r_a_t_o_r___a_p_i.html", "group___c_o_m_p_a_r_a_t_o_r___a_p_i" ],
    [ "CRC Interface", "group___c_r_c___a_p_i.html", "group___c_r_c___a_p_i" ],
    [ "CTSU Interface", "group___c_t_s_u___a_p_i.html", "group___c_t_s_u___a_p_i" ],
    [ "DAC Interface", "group___d_a_c___a_p_i.html", "group___d_a_c___a_p_i" ],
    [ "Display Interface", "group___d_i_s_p_l_a_y___a_p_i.html", "group___d_i_s_p_l_a_y___a_p_i" ],
    [ "DOC Interface", "group___d_o_c___a_p_i.html", "group___d_o_c___a_p_i" ],
    [ "ELC Interface", "group___e_l_c___a_p_i.html", "group___e_l_c___a_p_i" ],
    [ "Ethernet Interface", "group___e_t_h_e_r___a_p_i.html", "group___e_t_h_e_r___a_p_i" ],
    [ "Ethernet PHY Interface", "group___e_t_h_e_r___p_h_y___a_p_i.html", "group___e_t_h_e_r___p_h_y___a_p_i" ],
    [ "External IRQ Interface", "group___e_x_t_e_r_n_a_l___i_r_q___a_p_i.html", "group___e_x_t_e_r_n_a_l___i_r_q___a_p_i" ],
    [ "Flash Interface", "group___f_l_a_s_h___a_p_i.html", "group___f_l_a_s_h___a_p_i" ],
    [ "I2C Master Interface", "group___i2_c___m_a_s_t_e_r___a_p_i.html", "group___i2_c___m_a_s_t_e_r___a_p_i" ],
    [ "I2C Slave Interface", "group___i2_c___s_l_a_v_e___a_p_i.html", "group___i2_c___s_l_a_v_e___a_p_i" ],
    [ "I2S Interface", "group___i2_s___a_p_i.html", "group___i2_s___a_p_i" ],
    [ "I3C Interface", "group___i3_c___a_p_i.html", "group___i3_c___a_p_i" ],
    [ "IIR Interface", "group___i_i_r___a_p_i.html", "group___i_i_r___a_p_i" ],
    [ "I/O Port Interface", "group___i_o_p_o_r_t___a_p_i.html", "group___i_o_p_o_r_t___a_p_i" ],
    [ "JPEG Codec Interface", "group___j_p_e_g___a_p_i.html", "group___j_p_e_g___a_p_i" ],
    [ "Key Matrix Interface", "group___k_e_y_m_a_t_r_i_x___a_p_i.html", "group___k_e_y_m_a_t_r_i_x___a_p_i" ],
    [ "Low Power Modes Interface", "group___l_p_m___a_p_i.html", "group___l_p_m___a_p_i" ],
    [ "Low Voltage Detection Interface", "group___l_v_d___a_p_i.html", "group___l_v_d___a_p_i" ],
    [ "OPAMP Interface", "group___o_p_a_m_p___a_p_i.html", "group___o_p_a_m_p___a_p_i" ],
    [ "PDC Interface", "group___p_d_c___a_p_i.html", "group___p_d_c___a_p_i" ],
    [ "POEG Interface", "group___p_o_e_g___a_p_i.html", "group___p_o_e_g___a_p_i" ],
    [ "PTP Interface", "group___p_t_p___a_p_i.html", "group___p_t_p___a_p_i" ],
    [ "RTC Interface", "group___r_t_c___a_p_i.html", "group___r_t_c___a_p_i" ],
    [ "SD/MMC Interface", "group___s_d_m_m_c___a_p_i.html", "group___s_d_m_m_c___a_p_i" ],
    [ "SLCDC Interface", "group___s_l_c_d_c___a_p_i.html", "group___s_l_c_d_c___a_p_i" ],
    [ "SPI Interface", "group___s_p_i___a_p_i.html", "group___s_p_i___a_p_i" ],
    [ "SPI Flash Interface", "group___s_p_i___f_l_a_s_h___a_p_i.html", "group___s_p_i___f_l_a_s_h___a_p_i" ],
    [ "Three-Phase Interface", "group___t_h_r_e_e___p_h_a_s_e___a_p_i.html", "group___t_h_r_e_e___p_h_a_s_e___a_p_i" ],
    [ "Timer Interface", "group___t_i_m_e_r___a_p_i.html", "group___t_i_m_e_r___a_p_i" ],
    [ "Transfer Interface", "group___t_r_a_n_s_f_e_r___a_p_i.html", "group___t_r_a_n_s_f_e_r___a_p_i" ],
    [ "UART Interface", "group___u_a_r_t___a_p_i.html", "group___u_a_r_t___a_p_i" ],
    [ "USB Interface", "group___u_s_b___a_p_i.html", "group___u_s_b___a_p_i" ],
    [ "USB HCDC Interface", "group___u_s_b___h_c_d_c___a_p_i.html", "group___u_s_b___h_c_d_c___a_p_i" ],
    [ "USB HHID Interface", "group___u_s_b___h_h_i_d___a_p_i.html", "group___u_s_b___h_h_i_d___a_p_i" ],
    [ "USB HMSC Interface", "group___u_s_b___h_m_s_c___a_p_i.html", "group___u_s_b___h_m_s_c___a_p_i" ],
    [ "USB PCDC Interface", "group___u_s_b___p_c_d_c___a_p_i.html", "group___u_s_b___p_c_d_c___a_p_i" ],
    [ "USB PHID Interface", "group___u_s_b___p_h_i_d___a_p_i.html", null ],
    [ "USB PMSC Interface", "group___u_s_b___p_m_s_c___a_p_i.html", "group___u_s_b___p_m_s_c___a_p_i" ],
    [ "WDT Interface", "group___w_d_t___a_p_i.html", "group___w_d_t___a_p_i" ],
    [ "ADPCM Decoder Interface", "group___r_m___a_d_p_c_m___d_e_c_o_d_e_r___a_p_i.html", "group___r_m___a_d_p_c_m___d_e_c_o_d_e_r___a_p_i" ],
    [ "AUDIO PLAYBACK Interface", "group___a_u_d_i_o___p_l_a_y_b_a_c_k___a_p_i.html", "group___a_u_d_i_o___p_l_a_y_b_a_c_k___a_p_i" ],
    [ "BLE ABS Interface", "group___b_l_e___a_b_s___a_p_i.html", "group___b_l_e___a_b_s___a_p_i" ],
    [ "BLE Mesh Access Interface", "group___r_m___b_l_e___m_e_s_h___a_c_c_e_s_s___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___a_c_c_e_s_s___a_p_i" ],
    [ "BLE Mesh Interface", "group___r_m___b_l_e___m_e_s_h___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___a_p_i" ],
    [ "BLE Mesh Bearer Interface", "group___r_m___b_l_e___m_e_s_h___b_e_a_r_e_r___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___b_e_a_r_e_r___a_p_i" ],
    [ "BLE Mesh Model Configuration Client Interface", "group___r_m___b_l_e___m_e_s_h___c_o_n_f_i_g___c_l_i_e_n_t___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___c_o_n_f_i_g___c_l_i_e_n_t___a_p_i" ],
    [ "BLE Mesh Health Server Interface", "group___r_m___b_l_e___m_e_s_h___h_e_a_l_t_h___s_e_r_v_e_r___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___h_e_a_l_t_h___s_e_r_v_e_r___a_p_i" ],
    [ "BLE Mesh Lower Trans Interface", "group___r_m___b_l_e___m_e_s_h___l_o_w_e_r___t_r_a_n_s___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___l_o_w_e_r___t_r_a_n_s___a_p_i" ],
    [ "BLE Mesh Model Client Interface", "group___r_m___b_l_e___m_e_s_h___m_o_d_e_l___c_l_i_e_n_t___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___m_o_d_e_l___c_l_i_e_n_t___a_p_i" ],
    [ "BLE Mesh Model Server Interface", "group___r_m___b_l_e___m_e_s_h___m_o_d_e_l___s_e_r_v_e_r___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___m_o_d_e_l___s_e_r_v_e_r___a_p_i" ],
    [ "BLE Mesh Network Interface", "group___r_m___b_l_e___m_e_s_h___n_e_t_w_o_r_k___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___n_e_t_w_o_r_k___a_p_i" ],
    [ "BLE Mesh Provision Interface", "group___r_m___b_l_e___m_e_s_h___p_r_o_v_i_s_i_o_n___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___p_r_o_v_i_s_i_o_n___a_p_i" ],
    [ "BLE Mesh Scene Server Interface", "group___r_m___b_l_e___m_e_s_h___s_c_e_n_e___s_e_r_v_e_r___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___s_c_e_n_e___s_e_r_v_e_r___a_p_i" ],
    [ "BLE Mesh Upper Trans Interface", "group___r_m___b_l_e___m_e_s_h___u_p_p_e_r___t_r_a_n_s___a_p_i.html", "group___r_m___b_l_e___m_e_s_h___u_p_p_e_r___t_r_a_n_s___a_p_i" ],
    [ "Block Media Interface", "group___r_m___b_l_o_c_k___m_e_d_i_a___a_p_i.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___a_p_i" ],
    [ "Communicatons Middleware Interface", "group___r_m___c_o_m_m_s___a_p_i.html", "group___r_m___c_o_m_m_s___a_p_i" ],
    [ "FileX Block Media Port Interface", "group___r_m___f_i_l_e_x___b_l_o_c_k___m_e_d_i_a___a_p_i.html", "group___r_m___f_i_l_e_x___b_l_o_c_k___m_e_d_i_a___a_p_i" ],
    [ "FreeRTOS+FAT Port Interface", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t___a_p_i.html", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t___a_p_i" ],
    [ "FSXXXX Middleware Interface", "group___r_m___f_s_x_x_x_x___a_p_i.html", "group___r_m___f_s_x_x_x_x___a_p_i" ],
    [ "HS300X Middleware Interface", "group___r_m___h_s300_x___a_p_i.html", "group___r_m___h_s300_x___a_p_i" ],
    [ "LittleFS Interface", "group___r_m___l_i_t_t_l_e_f_s___a_p_i.html", "group___r_m___l_i_t_t_l_e_f_s___a_p_i" ],
    [ "BLE Mesh Bearer Platform Interface", "group___r_m___m_e_s_h___b_e_a_r_e_r___p_l_a_t_f_o_r_m___a_p_i.html", "group___r_m___m_e_s_h___b_e_a_r_e_r___p_l_a_t_f_o_r_m___a_p_i" ],
    [ "Interface", "group___m_o_t_o_r__120___c_o_n_t_r_o_l___a_p_i.html", "group___m_o_t_o_r__120___c_o_n_t_r_o_l___a_p_i" ],
    [ "Interface", "group___m_o_t_o_r__120___d_r_i_v_e_r___a_p_i.html", "group___m_o_t_o_r__120___d_r_i_v_e_r___a_p_i" ],
    [ "Motor angle Interface", "group___m_o_t_o_r___a_n_g_l_e___a_p_i.html", "group___m_o_t_o_r___a_n_g_l_e___a_p_i" ],
    [ "Motor Interface", "group___m_o_t_o_r___a_p_i.html", "group___m_o_t_o_r___a_p_i" ],
    [ "Motor current Interface", "group___m_o_t_o_r___c_u_r_r_e_n_t___a_p_i.html", "group___m_o_t_o_r___c_u_r_r_e_n_t___a_p_i" ],
    [ "Motor driver Interface", "group___m_o_t_o_r___d_r_i_v_e_r___a_p_i.html", "group___m_o_t_o_r___d_r_i_v_e_r___a_p_i" ],
    [ "Motor position Interface", "group___m_o_t_o_r___p_o_s_i_t_i_o_n___a_p_i.html", "group___m_o_t_o_r___p_o_s_i_t_i_o_n___a_p_i" ],
    [ "Motor speed Interface", "group___m_o_t_o_r___s_p_e_e_d___a_p_i.html", "group___m_o_t_o_r___s_p_e_e_d___a_p_i" ],
    [ "Touch Middleware Interface", "group___t_o_u_c_h___a_p_i.html", "group___t_o_u_c_h___a_p_i" ],
    [ "Virtual EEPROM Interface", "group___r_m___v_e_e___a_p_i.html", "group___r_m___v_e_e___a_p_i" ],
    [ "ZMOD4XXX Middleware Interface", "group___r_m___z_m_o_d4_x_x_x___a_p_i.html", "group___r_m___z_m_o_d4_x_x_x___a_p_i" ],
    [ "SCE Interface", "group___s_c_e___p_r_o_t_e_c_t_e_d___a_p_i.html", "group___s_c_e___p_r_o_t_e_c_t_e_d___a_p_i" ]
];