var group___r_e_n_e_s_a_s___m_o_d_u_l_e_s =
[
    [ "High-Speed Analog Comparator (r_acmphs)", "group___a_c_m_p_h_s.html", "group___a_c_m_p_h_s" ],
    [ "Low-Power Analog Comparator (r_acmplp)", "group___a_c_m_p_l_p.html", "group___a_c_m_p_l_p" ],
    [ "Analog to Digital Converter (r_adc)", "group___a_d_c.html", "group___a_d_c" ],
    [ "Asynchronous General Purpose Timer (r_agt)", "group___a_g_t.html", "group___a_g_t" ],
    [ "Bluetooth Low Energy Library (r_ble)", "group___b_l_e.html", "group___b_l_e" ],
    [ "Clock Frequency Accuracy Measurement Circuit (r_cac)", "group___c_a_c.html", "group___c_a_c" ],
    [ "Controller Area Network (r_can)", "group___c_a_n.html", "group___c_a_n" ],
    [ "Clock Generation Circuit (r_cgc)", "group___c_g_c.html", "group___c_g_c" ],
    [ "Cyclic Redundancy Check (CRC) Calculator (r_crc)", "group___c_r_c.html", "group___c_r_c" ],
    [ "Capacitive Touch Sensing Unit (r_ctsu)", "group___c_t_s_u.html", "group___c_t_s_u" ],
    [ "Digital to Analog Converter (r_dac)", "group___d_a_c.html", "group___d_a_c" ],
    [ "Digital to Analog Converter (r_dac8)", "group___d_a_c8.html", "group___d_a_c8" ],
    [ "Direct Memory Access Controller (r_dmac)", "group___d_m_a_c.html", "group___d_m_a_c" ],
    [ "Data Operation Circuit (r_doc)", "group___d_o_c.html", "group___d_o_c" ],
    [ "D/AVE 2D Port Interface (r_drw)", "group___d_r_w.html", null ],
    [ "Data Transfer Controller (r_dtc)", "group___d_t_c.html", "group___d_t_c" ],
    [ "Event Link Controller (r_elc)", "group___e_l_c.html", "group___e_l_c" ],
    [ "Ethernet (r_ether)", "group___e_t_h_e_r.html", "group___e_t_h_e_r" ],
    [ "Ethernet PHY (r_ether_phy)", "group___e_t_h_e_r___p_h_y.html", "group___e_t_h_e_r___p_h_y" ],
    [ "High-Performance Flash Driver (r_flash_hp)", "group___f_l_a_s_h___h_p.html", "group___f_l_a_s_h___h_p" ],
    [ "Low-Power Flash Driver (r_flash_lp)", "group___f_l_a_s_h___l_p.html", "group___f_l_a_s_h___l_p" ],
    [ "Graphics LCD Controller (r_glcdc)", "group___g_l_c_d_c.html", "group___g_l_c_d_c" ],
    [ "General PWM Timer (r_gpt)", "group___g_p_t.html", "group___g_p_t" ],
    [ "General PWM Timer Three-Phase Motor Control Driver (r_gpt_three_phase)", "group___g_p_t___t_h_r_e_e___p_h_a_s_e.html", "group___g_p_t___t_h_r_e_e___p_h_a_s_e" ],
    [ "Interrupt Controller Unit (r_icu)", "group___i_c_u.html", "group___i_c_u" ],
    [ "I2C Master on IIC (r_iic_master)", "group___i_i_c___m_a_s_t_e_r.html", "group___i_i_c___m_a_s_t_e_r" ],
    [ "I2C Slave on IIC (r_iic_slave)", "group___i_i_c___s_l_a_v_e.html", "group___i_i_c___s_l_a_v_e" ],
    [ "I/O Ports (r_ioport)", "group___i_o_p_o_r_t.html", "group___i_o_p_o_r_t" ],
    [ "Independent Watchdog Timer (r_iwdt)", "group___i_w_d_t.html", "group___i_w_d_t" ],
    [ "JPEG Codec (r_jpeg)", "group___j_p_e_g.html", "group___j_p_e_g" ],
    [ "Key Interrupt (r_kint)", "group___k_i_n_t.html", "group___k_i_n_t" ],
    [ "Low Power Modes (r_lpm)", "group___l_p_m.html", "group___l_p_m" ],
    [ "Low Voltage Detection (r_lvd)", "group___l_v_d.html", "group___l_v_d" ],
    [ "Operational Amplifier (r_opamp)", "group___o_p_a_m_p.html", "group___o_p_a_m_p" ],
    [ "Octa Serial Peripheral Interface Flash (r_ospi)", "group___o_s_p_i.html", "group___o_s_p_i" ],
    [ "Parallel Data Capture (r_pdc)", "group___p_d_c.html", "group___p_d_c" ],
    [ "Port Output Enable for GPT (r_poeg)", "group___p_o_e_g.html", "group___p_o_e_g" ],
    [ "Quad Serial Peripheral Interface Flash (r_qspi)", "group___q_s_p_i.html", "group___q_s_p_i" ],
    [ "Realtime Clock (r_rtc)", "group___r_t_c.html", "group___r_t_c" ],
    [ "Serial Communications Interface (SCI) I2C (r_sci_i2c)", "group___s_c_i___i2_c.html", "group___s_c_i___i2_c" ],
    [ "Serial Communications Interface (SCI) SPI (r_sci_spi)", "group___s_c_i___s_p_i.html", "group___s_c_i___s_p_i" ],
    [ "Serial Communications Interface (SCI) UART (r_sci_uart)", "group___s_c_i___u_a_r_t.html", "group___s_c_i___u_a_r_t" ],
    [ "Sigma Delta Analog to Digital Converter (r_sdadc)", "group___s_d_a_d_c.html", "group___s_d_a_d_c" ],
    [ "SD/MMC Host Interface (r_sdhi)", "group___s_d_h_i.html", "group___s_d_h_i" ],
    [ "Segment LCD Controller (r_slcdc)", "group___s_l_c_d_c.html", "group___s_l_c_d_c" ],
    [ "Serial Peripheral Interface (r_spi)", "group___s_p_i.html", "group___s_p_i" ],
    [ "Serial Sound Interface (r_ssi)", "group___s_s_i.html", "group___s_s_i" ],
    [ "USB (r_usb_basic)", "group___u_s_b.html", "group___u_s_b" ],
    [ "USB Composite Class (r_usb_composite)", "group___u_s_b___c_o_m_p_o_s_i_t_e.html", null ],
    [ "USB Host Communications Device Class Driver (r_usb_hcdc)", "group___u_s_b___h_c_d_c.html", null ],
    [ "USB Host Human Interface Device Class Driver (r_usb_hhid)", "group___u_s_b___h_h_i_d.html", "group___u_s_b___h_h_i_d" ],
    [ "USB Host Mass Storage Class Driver (r_usb_hmsc)", "group___u_s_b___h_m_s_c.html", "group___u_s_b___h_m_s_c" ],
    [ "USB Host Vendor Class (r_usb_hvnd)", "group___u_s_b___h_v_n_d.html", null ],
    [ "USB Peripheral Communications Device Class (r_usb_pcdc)", "group___u_s_b___p_c_d_c.html", null ],
    [ "USB Peripheral Human Interface Device Class (r_usb_phid)", "group___u_s_b___p_h_i_d.html", null ],
    [ "USB Peripheral Mass Storage Class (r_usb_pmsc)", "group___u_s_b___p_m_s_c.html", null ],
    [ "USB Peripheral Vendor Class (r_usb_pvnd)", "group___u_s_b___p_v_n_d.html", null ],
    [ "Watchdog Timer (r_wdt)", "group___w_d_t.html", "group___w_d_t" ],
    [ "AWS PKCS11 PAL (rm_aws_pkcs11_pal)", "group___a_w_s___p_k_c_s11___p_a_l.html", null ],
    [ "AWS PKCS11 PAL LITTLEFS (rm_aws_pkcs11_pal_littlefs)", "group___a_w_s___p_k_c_s11___p_a_l___l_i_t_t_l_e_f_s.html", null ],
    [ "Bluetooth Low Energy Abstraction (rm_ble_abs)", "group___b_l_e___a_b_s.html", "group___b_l_e___a_b_s" ],
    [ "SD/MMC Block Media Implementation (rm_block_media_sdmmc)", "group___r_m___b_l_o_c_k___m_e_d_i_a___s_d_m_m_c.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___s_d_m_m_c" ],
    [ "USB HMSC Block Media Implementation (rm_block_media_usb)", "group___r_m___b_l_o_c_k___m_e_d_i_a___u_s_b.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___u_s_b" ],
    [ "SEGGER emWin Port (rm_emwin_port)", "group___r_m___e_m_w_i_n___p_o_r_t.html", null ],
    [ "FreeRTOS+FAT Port (rm_freertos_plus_fat)", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t.html", "group___r_m___f_r_e_e_r_t_o_s___p_l_u_s___f_a_t" ],
    [ "FreeRTOS Plus TCP (rm_freertos_plus_tcp)", "group___f_r_e_e_r_t_o_s___p_l_u_s___t_c_p.html", null ],
    [ "FreeRTOS Port (rm_freertos_port)", "group___r_m___f_r_e_e_r_t_o_s___p_o_r_t.html", null ],
    [ "RTOS Context Management (rm_tz_context)", "group___r_m___t_z___c_o_n_t_e_x_t.html", null ],
    [ "LittleFS Flash Port (rm_littlefs_flash)", "group___r_m___l_i_t_t_l_e_f_s___f_l_a_s_h.html", "group___r_m___l_i_t_t_l_e_f_s___f_l_a_s_h" ],
    [ "Motor Current (rm_motor_current)", "group___m_o_t_o_r___c_u_r_r_e_n_t.html", "group___m_o_t_o_r___c_u_r_r_e_n_t" ],
    [ "Motor Driver (rm_motor_driver)", "group___m_o_t_o_r___d_r_i_v_e_r.html", "group___m_o_t_o_r___d_r_i_v_e_r" ],
    [ "Motor Angle and Speed Estimation (rm_motor_estimate)", "group___m_o_t_o_r___e_s_t_i_m_a_t_e.html", "group___m_o_t_o_r___e_s_t_i_m_a_t_e" ],
    [ "Motor Sensorless Vector Control (rm_motor_sensorless)", "group___m_o_t_o_r___s_e_n_s_o_r_l_e_s_s.html", "group___m_o_t_o_r___s_e_n_s_o_r_l_e_s_s" ],
    [ "Motor Speed (rm_motor_speed)", "group___m_o_t_o_r___s_p_e_e_d.html", "group___m_o_t_o_r___s_p_e_e_d" ],
    [ "Crypto Middleware (rm_psa_crypto)", "group___r_m___p_s_a___c_r_y_p_t_o.html", "group___r_m___p_s_a___c_r_y_p_t_o" ],
    [ "Capacitive Touch Middleware (rm_touch)", "group___t_o_u_c_h.html", "group___t_o_u_c_h" ],
    [ "Virtual EEPROM (rm_vee_flash)", "group___r_m___v_e_e___f_l_a_s_h.html", "group___r_m___v_e_e___f_l_a_s_h" ],
    [ "AWS Device Provisioning", "group___d_e_v_i_c_e___p_r_o_v_i_s_i_o_n_i_n_g.html", null ],
    [ "AWS MQTT", "group___a_w_s___m_q_t_t.html", null ],
    [ "Wifi Middleware (rm_wifi_onchip_silex)", "group___w_i_f_i___o_n_c_h_i_p___s_i_l_e_x.html", "group___w_i_f_i___o_n_c_h_i_p___s_i_l_e_x" ],
    [ "AWS Secure Sockets", "group___a_w_s___s_e_c_u_r_e___s_o_c_k_e_t_s.html", null ]
];