var searchData=
[
  ['spp_20ble_20abstraction_20_28rm_5fble_5fabs_5fspp_29',['SPP BLE Abstraction (rm_ble_abs_spp)',['../group___b_l_e___a_b_s___s_p_p.html',1,'']]],
  ['security',['Security',['../group___r_e_n_e_s_a_s___s_e_c_u_r_i_t_y___i_n_t_e_r_f_a_c_e_s.html',1,'']]],
  ['security',['Security',['../group___r_e_n_e_s_a_s___s_e_c_u_r_i_t_y___m_o_d_u_l_e_s.html',1,'']]],
  ['sensor',['Sensor',['../group___r_e_n_e_s_a_s___s_e_n_s_o_r___i_n_t_e_r_f_a_c_e_s.html',1,'']]],
  ['sensor',['Sensor',['../group___r_e_n_e_s_a_s___s_e_n_s_o_r___m_o_d_u_l_e_s.html',1,'']]],
  ['storage',['Storage',['../group___r_e_n_e_s_a_s___s_t_o_r_a_g_e___i_n_t_e_r_f_a_c_e_s.html',1,'']]],
  ['storage',['Storage',['../group___r_e_n_e_s_a_s___s_t_o_r_a_g_e___m_o_d_u_l_e_s.html',1,'']]],
  ['system',['System',['../group___r_e_n_e_s_a_s___s_y_s_t_e_m___i_n_t_e_r_f_a_c_e_s.html',1,'']]],
  ['system',['System',['../group___r_e_n_e_s_a_s___s_y_s_t_e_m___m_o_d_u_l_e_s.html',1,'']]],
  ['sensor_20middleware_20interface',['SENSOR Middleware Interface',['../group___r_m___a_i_r___s_e_n_s_o_r___a_p_i.html',1,'']]],
  ['smbus_20communication_20device_20_28rm_5fcomms_5fsmbus_29',['SMBUS Communication Device (rm_comms_smbus)',['../group___r_m___c_o_m_m_s___s_m_b_u_s.html',1,'']]],
  ['segger_20emwin_20ra_20port_20_28rm_5femwin_5fport_29',['SEGGER emWin RA Port (rm_emwin_port)',['../group___r_m___e_m_w_i_n___p_o_r_t.html',1,'']]],
  ['secure_20key_20injection_20_28r_5frsip_5fkey_5finjection_29',['Secure Key Injection (r_rsip_key_injection)',['../group___r_s_i_p___k_e_y___i_n_j_e_c_t_i_o_n.html',1,'']]],
  ['spi_20_28r_5fsau_5fspi_29',['SPI (r_sau_spi)',['../group___s_a_u___s_p_i.html',1,'']]],
  ['secure_20key_20injection_20_28r_5fsce_5fkey_5finjection_29',['Secure Key Injection (r_sce_key_injection)',['../group___s_c_e___k_e_y___i_n_j_e_c_t_i_o_n.html',1,'']]],
  ['sce_20key_20injection_20interface',['SCE key injection Interface',['../group___s_c_e___k_e_y___i_n_j_e_c_t_i_o_n___a_p_i.html',1,'']]],
  ['sce_20protected_20mode',['SCE Protected Mode',['../group___s_c_e___p_r_o_t_e_c_t_e_d.html',1,'']]],
  ['sce_20interface',['SCE Interface',['../group___s_c_e___p_r_o_t_e_c_t_e_d___a_p_i.html',1,'']]],
  ['secure_20crypto_20engine_20_28r_5fsce_5fprotected_5fcavp_29',['Secure Crypto Engine (r_sce_protected_cavp)',['../group___s_c_e___p_r_o_t_e_c_t_e_d___c_a_v_p.html',1,'']]],
  ['spi_20_28r_5fsci_5fb_5fspi_29',['SPI (r_sci_b_spi)',['../group___s_c_i___b___s_p_i.html',1,'']]],
  ['smci_20_28r_5fsci_5fsmci_29',['SMCI (r_sci_smci)',['../group___s_c_i___s_m_c_i.html',1,'']]],
  ['spi_20_28r_5fsci_5fspi_29',['SPI (r_sci_spi)',['../group___s_c_i___s_p_i.html',1,'']]],
  ['sdadc_20channel_20configuration_20_28r_5fsdadc_29',['SDADC Channel Configuration (r_sdadc)',['../group___s_d_a_d_c.html',1,'']]],
  ['sdadc_5fb_20channel_20configuration_20_28r_5fsdadc_5fb_29',['SDADC_B Channel Configuration (r_sdadc_b)',['../group___s_d_a_d_c___b.html',1,'']]],
  ['sd_2fmmc_20_28r_5fsdhi_29',['SD/MMC (r_sdhi)',['../group___s_d_h_i.html',1,'']]],
  ['sd_2fmmc_20interface',['SD/MMC Interface',['../group___s_d_m_m_c___a_p_i.html',1,'']]],
  ['segment_20lcd_20_28r_5fslcdc_29',['Segment LCD (r_slcdc)',['../group___s_l_c_d_c.html',1,'']]],
  ['slcdc_20interface',['SLCDC Interface',['../group___s_l_c_d_c___a_p_i.html',1,'']]],
  ['smci_20interface',['SMCI Interface',['../group___s_m_c_i___a_p_i.html',1,'']]],
  ['spi_20_28r_5fspi_29',['SPI (r_spi)',['../group___s_p_i.html',1,'']]],
  ['spi_20interface',['SPI Interface',['../group___s_p_i___a_p_i.html',1,'']]],
  ['spi_20_28r_5fspi_5fb_29',['SPI (r_spi_b)',['../group___s_p_i___b.html',1,'']]],
  ['spi_20flash_20interface',['SPI Flash Interface',['../group___s_p_i___f_l_a_s_h___a_p_i.html',1,'']]]
];
